import { visit } from "unist-util-visit"
import { Root, Element } from "hast"
import { QuartzTransformerPlugin } from "../types"
import { lookup, srcsetOf } from "../../imageManifest"

/**
 * Upgrades images written in the body of a note into responsive `<picture>` elements,
 * using the derivatives generated by scripts/prepare-images.mjs.
 *
 * Without this, Quartz serves whatever came out of the camera: a 2500px JPEG with no
 * width or height, which is both heavy and a source of layout shift. Tiles already go
 * through the manifest via ProjectTile; this does the same for body images so both
 * routes behave alike.
 *
 * An animated source becomes a `<video>` rather than a `<picture>`, because video
 * compression carries every frame of the clip for a fraction of what an animated WebP
 * costs at a fifth of the frames. It is emitted without `autoplay`: the poster is the
 * still first frame, nothing moves until the visitor presses play, and with
 * `preload="none"` not a byte of the video is fetched until they do. That makes
 * `prefers-reduced-motion` correct by construction rather than by media query, and it
 * satisfies WCAG 2.2.2 — the animation is pausable because it was never running.
 *
 * An image with no manifest entry is left exactly as it was, so an image dropped in
 * before the pipeline has run still renders.
 */

const DEFAULT_SIZES = "(min-width: 48rem) 46rem, 100vw"

function source(type: string, srcset: string | undefined, media?: string): Element | null {
  if (!srcset) return null
  return {
    type: "element",
    tagName: "source",
    properties: { type, srcSet: srcset, sizes: DEFAULT_SIZES, ...(media ? { media } : {}) },
    children: [],
  }
}

export const ResponsiveImages: QuartzTransformerPlugin = () => {
  return {
    name: "ResponsiveImages",
    htmlPlugins() {
      return [
        () => {
          return (tree: Root) => {
            visit(tree, "element", (node: Element, index, parent) => {
              if (node.tagName !== "img" || index === undefined || !parent) return
              // Already wrapped by an earlier pass.
              if ((parent as Element).tagName === "picture") return

              const entry = lookup(node.properties?.src as string | undefined)
              if (!entry) return

              const jpeg = entry.still.jpeg ?? []
              const fallback = jpeg[jpeg.length - 1]?.src
              if (!fallback) return

              // The alt text the author wrote describes the motion, so it becomes the
              // video's accessible label rather than being thrown away.
              const alt = typeof node.properties?.alt === "string" ? node.properties.alt : ""

              if (entry.video) {
                // `poster` takes a single URL with no <source> fallback, so it has to be
                // a format everything reads. WebP has been safe since Safari 14 and is
                // a quarter smaller than the JPEG here; AVIF still isn't.
                const webp = entry.still.webp ?? []
                const posterSrc = webp[webp.length - 1]?.src ?? fallback
                parent.children[index] = {
                  type: "element",
                  tagName: "video",
                  properties: {
                    src: entry.video.src,
                    poster: posterSrc,
                    controls: true,
                    loop: true,
                    muted: true,
                    playsInline: true,
                    preload: "none",
                    width: entry.width ?? undefined,
                    height: entry.height ?? undefined,
                    "aria-label": alt || undefined,
                    style: entry.width ? `max-width:${entry.width}px` : undefined,
                  },
                  children: [{ type: "text", value: alt }],
                } as Element
                return
              }

              const sources: Element[] = []
              if (entry.anim) {
                // No ffmpeg, so fall back to the animated WebP: a still for anyone who
                // asked for less motion, then the animation.
                const still = source(
                  "image/webp",
                  srcsetOf(entry.still.webp),
                  "(prefers-reduced-motion: reduce)",
                )
                if (still) sources.push(still)
                const anim = source("image/webp", `${entry.anim.src} ${entry.anim.w}w`)
                if (anim) sources.push(anim)
              } else {
                const avif = source("image/avif", srcsetOf(entry.still.avif))
                if (avif) sources.push(avif)
                const webp = source("image/webp", srcsetOf(entry.still.webp))
                if (webp) sources.push(webp)
              }

              const img: Element = {
                type: "element",
                tagName: "img",
                properties: {
                  ...node.properties,
                  src: fallback,
                  srcSet: srcsetOf(jpeg),
                  sizes: DEFAULT_SIZES,
                  width: entry.width ?? undefined,
                  height: entry.height ?? undefined,
                  loading: "lazy",
                  decoding: "async",
                },
                children: [],
              }

              parent.children[index] = {
                type: "element",
                tagName: "picture",
                // Never display an image above its intrinsic size — a small source
                // shown big is just blurry.
                properties: entry.width ? { style: `max-width:${entry.width}px` } : {},
                children: [...sources, img],
              } as Element
            })
          }
        },
      ]
    },
  }
}
